import { HomeService } from './../../services/home.service';
import { AuthService } from './../../services/auth/auth.service';
import { Component, OnInit } from '@angular/core';

// Generated by https://quicktype.io

export interface Response {
  message: string;
  user: User;
}

export interface User {
  _id: string;
  iat: number;
  exp: number;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  constructor(
    private authService: AuthService,
    private homeService: HomeService
  ) {}

  user_id: string;
  message: string;

  ngOnInit() {
    this.homeService.callSafeEndPoint().subscribe((data: Response) => {
      this.user_id = data.user._id;
      this.message = data.message;
    });
  }

  logout() {
    this.authService.logout();
  }
}
